name: max_dating_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.4
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  carousel_slider: ^4.2.1
  intl: ^0.17.0
  step_progress_indicator: ^1.0.2
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  image_picker: ^0.8.7+1
  firebase_storage: ^11.0.16
  cloud_firestore: ^4.4.5
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    